#!/usr/bin/env ruby

require 'twitter'

client = Twitter::REST::Client.new do |config|
	config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
	config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
end

args = Hash.new
args["result_type"] = "recent"

if ARGV[1]
	args["since_id"] = ARGV[1]
end

client.search(ARGV[0], args).each do |tweet|
	puts "# " + tweet.id.to_s
	puts tweet.text
end